# Site settings
title: Brian Moore
description: My GitHub Page.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Brian Moore

user_description: A driven student and software developer with experience in crafting reliable, efficient, and maintainable software.
Experience working with teams, collaborating to create elegant software solutions using modern software
engineering techniques. Excellent communication and collaboration skills. Able to learn quickly on the fly.

user_title: Software Developer
email: brianmoore890@gmail.com
twitter_username: PeterDIsMyHero
github_username:  brimoo
gplus_username:   null

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
